<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Ações</th>
            <th>
                <a href="<?= $this->url('application/default', ['controller' => 'race',
                    'action' => 'save'])?>" class="btn btn-default btn-sm pull-right">
                    <span class="glyphicon glyphicon-plus"></span> Novo</a>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($races as $race): ?>
        <tr>
            <td><?= $race->name ?></td>
            <td colspan="2">
                <a href="<?= $this->url('application/default', ['controller' => 'race',
                    'action' => 'simulation-modal', 'id' => $race->_id->{'$id'}])?>"
                    data-type="simulation-btn" class="btn btn-primary btn-xs">
                    <span class="glyphicon glyphicon-road"></span> Simulação</a>
                <a href="<?= $this->url('application/default', ['controller' => 'race',
                    'action' => 'save', 'id' => $race->_id->{'$id'}])?>" class="btn btn-default btn-xs">
                    <span class="glyphicon glyphicon-edit"></span> Editar</a>
                <a href="<?= $this->url('application/default', ['controller' => 'race',
                    'action' => 'delete', 'id' => $race->_id->{'$id'}])?>"
                    class="btn btn-danger btn-xs btn-remove-race"><span class="glyphicon glyphicon-remove"></span> Excluir
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="modal fade" data-type="simulation-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content" data-type="modal-content">
    </div>
  </div>
</div>
