<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
        aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Simular</h4>
</div>
<div class="modal-body" data-type="modal-body">
Essa corrida ainda não foi simulada!
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">
        <span class="glyphicon glyphicon-remove"></span> Cancelar
    </button>
    <!-- TODO This button must send a POST through AJAX to simulate a race, and must not be shown for simulated races -->
    <button type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-play"></span>Simular
    </button>
</div>
